# Generated by Django 4.2.7 on 2025-12-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_knowledgebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hospital name', max_length=255)),
                ('address', models.TextField(help_text='Full address of the hospital')),
                ('departments', models.JSONField(blank=True, default=list, help_text="List of departments available at this hospital (e.g., ['Cardiology', 'Emergency', 'Pediatrics'])")),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for location-based search', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for location-based search', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['name'],
            },
        ),
    ]
