# Generated by Django 4.2.7 on 2025-12-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Disease name', max_length=255)),
                ('symptoms', models.JSONField(blank=True, default=list, help_text="List of symptoms for this disease (e.g., ['fever', 'cough', 'headache'])")),
                ('department', models.CharField(help_text="Department that treats this disease (e.g., 'Cardiology', 'Emergency', 'Pediatrics')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the disease')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'ordering': ['name'],
            },
        ),
    ]
