# Generated by Django 4.2.7 on 2025-12-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='differentiating_factors',
            field=models.TextField(blank=True, help_text='Key symptoms or characteristics that differentiate this disease from others with similar symptoms. This helps doctors and AI distinguish between diseases that share common symptoms.'),
        ),
    ]
