# Generated by Django 4.2.7 on 2025-12-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_disease_differentiating_factors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A descriptive name for this access token (e.g., 'HuggingFace API', 'OpenAI API')", max_length=255)),
                ('token', models.TextField(help_text='The actual access token value')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this token is used for')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is currently active and usable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Access Token',
                'verbose_name_plural': 'Access Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
