# Generated by Django 4.2.7 on 2025-12-12 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='current_user',
            field=models.ForeignKey(blank=True, help_text='The user currently assigned to this token (null if available)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_access_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
