# Generated by Django 4.2.7 on 2025-12-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_accesstoken_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='admin_ai_access_token',
            field=models.TextField(blank=True, help_text='Admin-only HuggingFace access token for AI model access', null=True),
        ),
    ]
